### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Handsomekaizer** [cnrad/spbf#2]
Hello,
Please this script is not working, please can you upload to heroku or netlify to see if it works. I really need this thank you.

**Comment by cnrad** [comment]
It does work, you just need to run it locally in your terminal (or on a server I suppose)

You also need to have an etherscan api key stored in API_KEY in environment variables, that's how it connects to check the wallet

**Comment by cnrad** [comment]
If that still doesn't work, you can generate seed phrases and try manually with MetaMask at https://0-y.me

**Comment by Handsomekaizer** [comment]
Hello i am not really good with JavaScript please can you show me where to put the API KEY

**Comment by Handsomekaizer** [comment]
Please can you update the repo with the environment variable file and where the etherscan API should be placed. Please, because u have tried all possible means to do this and it still does not work
